import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useAuth } from '../contexts/authContext'


export default function Home() {
  const user = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          user.loggedIn ? 
          <Link href="/dashboard">
            Go to Dashboard
          </Link> :
          <Link href="/login">
            Go to Login
          </Link>
        }
      </main>
    </div>
  )
}


export function getServerSideProps({ req }) {
  
  return {
    props: {
      testProp: "whatever"
    }
  }
}